[config]
schemaVersion = "0.0.1"

[package]
namespace = "SGG_Modding"
name = "ModUtil"
versionNumber = "4.0.1"
description = "Utility mod for mod interactions within lua for SGG's games"
websiteUrl = "https://github.com/SGG-Modding/ModUtil"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.22"
SGG_Modding-DemonDaemon = "1.0.1"
SGG_Modding-ENVY = "1.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "libraries", "mods" ]
